[versions]
lombok = "1.18.36"
logback = "1.5.16"
slf4j = "2.0.16"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
logging-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logging-runtime = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }